SMILE-225-Create Practitioner Referring Resource
mednax-it/Omniparser_Schemas pull request #4
Opened 2023-01-09 22:58 UTC by amakineni

Create Practitioner Referring Resource on top of message header, facility, patient resources

2023-01-10 13:57 UTC, aajaddu requested changes

2023-01-10 13:57 UTC, aajaddu commented on hl7v2_default.json
> +                              "system": {"const": "http://hl7.org/fhir/sid/us-npi"},
Let's use the system uri for npi that was already created. You can find it in the CSP created specifically for the practitioner npi.

2023-01-10 13:57 UTC, aajaddu commented on hl7v2_default.json
> +          "ifNoneExist": {"const": "identifier=http://hl7.org/fhir/sid/us-npi|9999999999"}
The business identifier in the request conditional cannot be hardcoded and must match the value defined in the business identifier section above.

2023-01-12 15:38 UTC, amakineni commented on hl7v2_default.json
> +                              "system": {"const": "http://hl7.org/fhir/sid/us-npi"},
Due to merge conflicts with main, created another PR https://github.com/mednax-it/Omniparser_Schemas/pull/15 with requested changes.

2023-01-12 15:38 UTC, amakineni commented on hl7v2_default.json
> +          "ifNoneExist": {"const": "identifier=http://hl7.org/fhir/sid/us-npi|9999999999"}
Due to merge conflicts with main, created another PR https://github.com/mednax-it/Omniparser_Schemas/pull/15 with requested changes.

2023-01-12 15:39 UTC, closed without merging

2023-01-12 15:39 UTC, amakineni commented
Due to merge conflicts with main, created another PR https://github.com/mednax-it/Omniparser_Schemas/pull/15 with requested changes.