Add regression tests for related person subscriber pos 3
mednax-it/Omniparser_Schemas pull request #59
Opened 2023-07-18 15:54 UTC by amakineni

1. Add regression tests for related person subscriber position 3

2023-07-19 20:28 UTC, aajaddu requested changes

2023-07-19 20:28 UTC, aajaddu commented on tests/regression/reg_globals/reference_urls.py
> +RELATED_PERSON_INSURANCE_FULL_URL_3="urn:uuid:61ebe121-aa05-0002-0001-983a382abcd7"
If the index occurrence count is 0001 and not 0003 then to avoid redundancy, could we either:
- assign RELATED_PERSON_INSURANCE_FULL_URL_3 = RELATED_PERSON_INSURANCE_FULL_URL_1
- or just use RELATED_PERSON_INSURANCE_FULL_URL_1 and not have to create RELATED_PERSON_INSURANCE_FULL_URL3

2023-07-20 14:51 UTC, amakineni commented on tests/regression/reg_globals/reference_urls.py
> +RELATED_PERSON_INSURANCE_FULL_URL_3="urn:uuid:61ebe121-aa05-0002-0001-983a382abcd7"
Thanks for the caught Anupam. The IN1 position in test data file needs to be set to '3' to reflect the purpose of tests. So now the URL will be as below.
RELATED_PERSON_INSURANCE_FULL_URL_3="urn:uuid:61ebe121-aa05-0002-0003-983a382abcd7"

2023-07-20 15:53 UTC, aajaddu approved these changes

2023-07-20 15:53 UTC, merged